Repository 100-hours-a-week/3-team-modie-be, pull requests merged in 2025-04, with the labels that each got.

#121 feat: chat-exception 채팅작성 날짜가 이전이면 예외처리 추가
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
Labels: Feature

#123 fix: POST meets 상태번호 200고정에서 201로 수정
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
Labels: Fix

#122 Feat: Spring Boot 애플리케이션에 Prometheus 메트릭 노출 설정 적용
  build.gradle
  src/main/resources/application.yml
Labels: Feature

#124 feat: Timezone Asia/Seoul로 설정
  src/main/resources/application.yml
Labels: Fix

#126 fix: 유효하지 않은 인증정보 전달 시 응답바디 추가
  src/main/java/org/ktb/modie/core/interceptor/JwtAuthenticationFilter.java
Labels: Fix

#128 fix: complete meet when modified total cost to zero
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: 버그-일반

#129 Feat/cicd - 다운타임 최소화 기능 추가
  .github/workflows/cicd.yml
Labels: Feature

#135 feat: 헬스채크기반 롤백 기능 구현
  .github/workflows/cicd.yml
Labels: Feature

#127 Feature - 채팅 FCM 알림 기능 추가
  .gitignore
  build.gradle
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/domain/FcmToken.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/FcmTokenRequest.java
  src/main/java/org/ktb/modie/repository/FcmTokenRepository.java
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/service/FcmService.java
  src/main/resources/application.yml
Labels: Feature

#136 feat: api-throttling 1초에 5번 요청 차단
  build.gradle
  src/main/java/org/ktb/modie/core/interceptor/ApiThrottlingFilter.java
Labels: Feature

#142 Fix - chat alarm Firebase 환경 변수 처리
  build.gradle
  src/main/java/org/ktb/modie/config/FirebaseProperties.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/core/util/HashIdUtil.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatHistoryController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetResponse.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetSummaryDto.java
  src/main/java/org/ktb/modie/repository/ChatRepository.java
  src/main/java/org/ktb/modie/service/FcmService.java
  src/main/java/org/ktb/modie/service/MeetService.java
  src/main/resources/application.yml
Labels: Fix

#146 fix: 해싱 암호화 테스트를 위한 해싱 키 하드코딩
  src/main/resources/application.yml
Labels: 버그-일반

#143 fix: 모임수정 최소인원, 설정인원 예외처리 추가
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Fix

#149 Fix - 방장에게 채팅 알림 보내기
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
  src/main/java/org/ktb/modie/service/FcmService.java
Labels: Fix

#153 fix: merge dev to main
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/org/ktb/modie/ModieApplication.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/core/interceptor/ApiThrottlingFilter.java
  src/main/java/org/ktb/modie/core/interceptor/JwtAuthenticationFilter.java
  src/main/java/org/ktb/modie/core/util/HashIdUtil.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatHistoryController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/ChatDto.java
  src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetResponse.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetDto.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetSummaryDto.java
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/service/FcmService.java
  src/main/java/org/ktb/modie/service/MeetService.java
  src/main/resources/application.yml
Labels: 도와주세요!

#154 Fix - totalCost 최소값 유효성 검증
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetDto.java
  src/main/java/org/ktb/modie/presentation/v1/dto/UpdateMeetRequest.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Fix

#152 feat: add logging filter at http layer and aop logging in service layers
  Dockerfile
  build.gradle
  src/main/java/org/ktb/modie/ModieApplication.java
  src/main/java/org/ktb/modie/config/SwaggerConfig.java
  src/main/java/org/ktb/modie/core/interceptor/LoggingFilter.java
  src/main/java/org/ktb/modie/core/util/LoggingAspect.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserController.java
  src/main/resources/application.yml
  src/main/resources/logback-dev.properties
  src/main/resources/logback-local.properties
  src/main/resources/logback-prod.properties
  src/main/resources/logback-spring.xml
Labels: Feature

#158 feat: log저장폴더 생성 로직 추가 및 버전 명시
  .github/workflows/cicd.yml
Labels: Feature
