Repository 100-hours-a-week/3-team-modie-be, pull requests merged in 2025-03, with the labels that each got.

#20 feat: add custom error message
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/v1/dto/MeetDto.java
Labels: Feature

#25 Feature: entity & createMeet API & custom error code
  CHANGELOG.md
  src/main/java/org/ktb/modie/config/SwaggerConfig.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/domain/Meet.java
  src/main/java/org/ktb/modie/domain/User.java
  src/main/java/org/ktb/modie/domain/UserMeet.java
  src/main/java/org/ktb/modie/presentation/v1/controller/AuthController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/HealthCheckApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/HealthCheckController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetRequest.java
  src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetResponse.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetDto.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetListResponse.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetSummaryDto.java
  src/main/java/org/ktb/modie/presentation/v1/dto/UserDto.java
  src/main/java/org/ktb/modie/repository/MeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
  src/main/java/org/ktb/modie/v1/controller/AuthController.java
  src/main/java/org/ktb/modie/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/v1/controller/TestApi.java
  src/main/java/org/ktb/modie/v1/controller/TestController.java
  src/main/java/org/ktb/modie/v1/dto/UserDto.java
Labels: Feature

#27 API - 모임 참여
  .github/workflows/cicd.yml
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/domain/Meet.java
  src/main/java/org/ktb/modie/domain/User.java
  src/main/java/org/ktb/modie/domain/UserMeet.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/repository/UserRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Feature

#29 feat: get meet
  src/main/java/org/ktb/modie/domain/Meet.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetRequest.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetDto.java
  src/main/java/org/ktb/modie/presentation/v1/dto/UserDto.java
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/repository/UserRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Feature

#49 be-prod CICD 파이프라인 구축 및 자동 롤백 기능 추가
  .github/workflows/cicd-prod.yml
  .github/workflows/cicd.yml
Labels: Feature

#38 feat: update meet api
  src/main/java/org/ktb/modie/domain/Meet.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/UpdateMeetRequest.java
  src/main/java/org/ktb/modie/presentation/v1/dto/UpdateMeetResponse.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Feature

#40 API - 모임 나가기
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/domain/User.java
  src/main/java/org/ktb/modie/domain/UserMeet.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/repository/MeetRepository.java
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/repository/UserRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Feature

#36 API - 모임 완료
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Feature

#45 API - 정산 내역 업데이트
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/UpdatePaymentRequest.java
  src/main/java/org/ktb/modie/presentation/v1/dto/UpdatePaymentResponse.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Feature

#48 feat: get user profile
  src/main/java/org/ktb/modie/presentation/v1/controller/UserApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetDto.java
  src/main/java/org/ktb/modie/presentation/v1/dto/UserResponse.java
  src/main/java/org/ktb/modie/service/UserService.java
Labels: Feature

#43 feat: 채팅 구현
  src/main/java/org/ktb/modie/config/AppConfig.java
  src/main/java/org/ktb/modie/config/WebSocketConfig.java
  src/main/java/org/ktb/modie/domain/Chat.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatHistoryController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/ChatDto.java
  src/main/java/org/ktb/modie/presentation/v1/dto/ChatMessageDto.java
  src/main/java/org/ktb/modie/repository/ChatRepository.java
  src/main/java/org/ktb/modie/repository/MeetRepository.java
  src/main/java/org/ktb/modie/repository/UserRepository.java
  src/main/java/org/ktb/modie/service/ChatService.java
Labels: Feature

#60 Fix - 모임 나가기 예외추가
  src/main/java/org/ktb/modie/config/WebConfig.java
  src/main/java/org/ktb/modie/config/WebSocketConfig.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Fix

#33 API - 모임 목록 조회
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/repository/MeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Feature

#62 feat: Docker 실행 시 JWT 시크릿 키 & 카카오 API 키 환경 변수 추가
  .github/workflows/cicd.yml
Labels: Feature

#64 Fix - 모임 생성 예외추가
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetRequest.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: 버그-일반

#67 feat: jwt 로그인 기능 구현
  build.gradle
  src/main/java/org/ktb/modie/config/WebConfig.java
  src/main/java/org/ktb/modie/core/interceptor/JwtAuthenticationFilter.java
  src/main/java/org/ktb/modie/presentation/v1/controller/AuthController.java
  src/main/java/org/ktb/modie/service/JwtService.java
  src/main/java/org/ktb/modie/service/UserService.java
  src/main/resources/application.yml
Labels: Fix

#68 fix: 환경변수 추가
  .github/workflows/cicd.yml
Labels: Fix

#69 Fix/env
  build.gradle
  src/main/java/org/ktb/modie/config/SwaggerConfig.java
  src/main/java/org/ktb/modie/core/interceptor/JwtAuthenticationFilter.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetSummaryDto.java
  src/main/java/org/ktb/modie/service/JwtService.java
Labels: Fix

#70 fix: SwaggerConfig.java
  src/main/java/org/ktb/modie/config/SwaggerConfig.java
Labels: Fix

#75 feat: update meet amount and change description updatepayment
  src/main/java/org/ktb/modie/config/SwaggerConfig.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/UserController.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Feature

#76 fix: 기존 프로젝트 구조와 채팅 DTO 구조 통일 및 국내 시간대로 통일
  src/main/java/org/ktb/modie/config/WebSocketConfig.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatHistoryController.java
  src/main/java/org/ktb/modie/presentation/v1/dto/ChatDto.java
Labels: Feature

#90 Fix - 모임 목록 조회 관련 예외처리
  src/main/java/org/ktb/modie/repository/MeetRepository.java
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Fix

#88 Fix - 모임 나가기 관련 예외처리
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Fix

#84 Fix - 모임 생성 예외처리2
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/core/handler/GlobalExceptionHandler.java
  src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetRequest.java
  src/main/java/org/ktb/modie/service/MeetService.java
  src/main/resources/application.yml
Labels: Fix

#91 FIX - 모임목록조회 수정
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
  src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
  src/main/java/org/ktb/modie/repository/MeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Fix

#94 FIX - editorConfig format 통일
  src/main/java/org/ktb/modie/core/handler/GlobalExceptionHandler.java
Labels: Fix

#96 FIX - edit SwaggerConfig
  src/main/java/org/ktb/modie/config/SwaggerConfig.java
Labels: Fix

#85 fix/update account
  src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
  src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
  src/main/java/org/ktb/modie/domain/User.java
  src/main/java/org/ktb/modie/presentation/v1/dto/UpdateAccountRequest.java
  src/main/java/org/ktb/modie/service/UserService.java
Labels: Fix

#95 fix: empty user id sets guest and seperate get meet role method
  src/main/java/org/ktb/modie/core/interceptor/JwtAuthenticationFilter.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Fix

#101 FIX - findFilteredMeets Query at MeetRepository
  src/main/java/org/ktb/modie/repository/MeetRepository.java
Labels: Feature, Fix

#102 fix : import package for build
  src/main/java/org/ktb/modie/domain/Meet.java
Labels: Fix

#100 fix: meetrule 수정 완료
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
Labels: Fix

#105 fix: update account with empty string
  src/main/java/org/ktb/modie/service/UserService.java
Labels: Fix

#106 Feat - 모임 목록 조회 정렬(모임 시각 기준 DESC)
  src/main/java/org/ktb/modie/repository/MeetRepository.java
Labels: Feature

#110 fix: merge dev to main
  src/main/java/org/ktb/modie/domain/Meet.java
  src/main/java/org/ktb/modie/presentation/v1/dto/MeetSummaryDto.java
  src/main/java/org/ktb/modie/repository/MeetRepository.java
  src/main/java/org/ktb/modie/repository/UserMeetRepository.java
  src/main/java/org/ktb/modie/service/MeetService.java
  src/main/java/org/ktb/modie/service/UserService.java
Labels: 버그-일반

#111 fix : edit MeetRepository findFilteredMeets Query for Order #103
  src/main/java/org/ktb/modie/repository/MeetRepository.java
Labels: Fix

#113 FIX - 모임 목록 조회 쿼리 수정
  src/main/java/org/ktb/modie/repository/MeetRepository.java
Labels: Fix

#120 feat: chat-exception 추가
  src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
Labels: Feature
